import { Noto_Sans_Bengali } from "next/font/google";

import "./globals.css";
const notoSansBengali = Noto_Sans_Bengali({
  subsets: ["bengali"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={notoSansBengali.className}>
      <body className={`antialiased `}>{children}</body>
    </html>
  );
}
